site_name: COBLE Documentation
site_description: Documentation for COBLE - COnda BuiLdEr
site_author: RSE team at ICR
repo_url: https://github.com/ICR-RSE-Group/coble
repo_name: icr-rse/coble

theme:
  name: material
  logo: coble.png
  favicon: coble.png
  palette:
    # Light mode
    - scheme: default
      primary: light green
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: light green
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true  
  
nav:
  - Overview:
    - Home: index.md
    - Installation: overview/install.md
    - Motivation: overview/motivation.md  
    - Visualisation: overview/network.md
  - COBLE:
    - Recipe-anatomy: coble/anatomy.md
    - Outputs-anatomy: coble/outputs.md
    - Finding-packages: coble/finding.md
    - Workflow: coble/workflow.md
    - Libraries: coble/libraries.md
    - icr-cluster: coble/icr.md
    - hpc-cluster: coble/hpc.md    
  - Recipes:
    - Overview: recipes.md
    - Basic: recipes/basic.md
    - Bash: recipes/bash.md
    - Versions: recipes/versions.md
    - Bioinformatics: recipes/bioinf.md
  - Tutorials:
    - Overview: tutorial.md
    - SYLVER(Find): tutorials/sylver.md
    - CountReg(Fix): tutorials/countreg.md
    - Troubleshooting: tutorials/troubleshooting.md
  - Containers: 
    - Containers: containers.md    
    - Docker-Singularity: containers/docker-build.md  
  - Troubleshooting: tutorials/troubleshooting.md
  - About: about.md
