#!/bin/bash

# Detect install context (bin vs code dir)
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
script_base="$(basename "$script_dir")"
if [[ "$script_base" == "bin" ]]; then
	install_context="conda"
else
	install_context="github"
fi
# Optionally, you can use $install_context in help or logic
# Detect operating system
os_type="$(uname)"
echo "[coble] Detected OS: $os_type, Install context: $install_context" >&2

show_help() {
	echo "Usage: $0 <command> [options]"
	echo "  recipe   get a starter recipe of 5 given options"
	echo "  build    build the conda enviroment from scratch clean"
	echo "  update   update an existing environment from the changes to the recipe input"
	echo "Example:"
	echo "  $0 recipe --input my.cbl --flavour basic"
	echo "  $0 build --input my.cbl --env my-env"
}

start_time=$(date +%s)
echo "[coble] Starting coble at $(date)" >&2

# Global help option
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
	show_help
	exit 0
fi

# If the first argument is 'recipe', call coble-template.sh and exit
if [[ "$1" == "recipe" ]]; then
	script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	"$script_dir/coble-template.sh" "${@:2}"
	exit $?
fi

# If the first argument is 'build or update', call a succession of scripts checking status and exit
if [[ "$1" == "build" || "$1" == "update" ]]; then	
	script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	# TODO SKIP THIS IF sh passed in as input
	echo "[*coble 1/5] Resolving yml..." >&2
	finds=$("$script_dir/coble-resolve.sh" "${@:2}")
	if [[ "$finds" == "Y" ]]; then
		echo "[*coble] Finds were resolved, please check the yml input before resuming." >&2
		exit 0
	fi	
	
	echo "[*coble 2/5] Resolved yml, proceeding to rationalise." >&2
	success=$("$script_dir/coble-rationalise.sh" "${@:2}")
				
	echo "[*coble 3/5] Rationalised yml, proceeding to recipise." >&2	
	mapfile -t result < <("$script_dir/coble-recipise.sh" "${@:2}")
	success="${result[0]}"
	recipe_file="${result[1]}"
	if [[ "$success" == "N" ]]; then
		echo "[*coble] Error in creating recipe, please correct input before resuming." >&2
		exit 0
	fi	
	
	done_recipe="$recipe_file".done.sh
	summary_file="$recipe_file.summary.txt"
	capture_file="$recipe_file.capture.cbl"
	
	if [[ "$1" == "build" ]]; then
	    echo "[*coble 3/5] Created recipe, rebuilding environment." >&2
	    : > "$done_recipe"
		: > "$summary_file"
	elif [[ "$1" == "update" ]]; then	
	    if [[ ! -f "$done_recipe" ]]; then
			: > "$done_recipe"
			: > "$summary_file"			
			echo "[*coble 3/5] Created recipe, building environment." >&2
		else
		    
			echo "[*coble 3/5] Created recipe, updating environment." >&2
		fi
	else
		echo "[*coble] Unknown command: $1" >&2
		exit 1
	fi
		
	
	

	update_success=$("$script_dir/coble-update.sh" --done-recipe "$done_recipe" --all-recipe "$recipe_file")
	if [[ $? -ne 0 ]]; then		 
		echo "[*coble] Error in updating recipe, please review logs before resuming." >&2
		exit 0
	fi		
	echo "[*coble 4/5] Created recipe, proceeding to creation." >&2
	recipe_file="$recipe_file".delta.sh
	result=$("$script_dir/coble-create.sh" --recipe "$recipe_file" "${@:2}")
	if [[ $? -ne 0 ]]; then		 
		echo "[*coble] Error in environment creation, please review logs before resuming." >&2

		end_time=$(date +%s)
	    duration=$((end_time - start_time))
	    hours=$((duration / 3600))
	    minutes=$(((duration % 3600) / 60))
	    seconds=$((duration % 60))
	    echo "[*coble] Time taken to get here $(date) (Duration: ${hours}h ${minutes}m ${seconds}s)" >&2	
		exit 0
	fi
	
	echo "[*coble 5/5] Created env, proceeding to capture." >&2	
	recipe_dir="$(dirname "$recipe_file")"	
	result=$("$script_dir/coble-capture.sh" --outdir "$recipe_dir" --output "$capture_file" "${@:2}")
		
	echo "[*coble] Environment creation complete." >&2
	end_time=$(date +%s)
	duration=$((end_time - start_time))
	hours=$((duration / 3600))
	minutes=$(((duration % 3600) / 60))
	seconds=$((duration % 60))
	echo "[*coble] Completed coble at $(date) (Duration: ${hours}h ${minutes}m ${seconds}s)" >&2	
	exit $?
fi

echo "[*coble] Not a valid command provided: $1." >&2
show_help