{% set name = "coble" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: generic

requirements:
  run:
    - bash

test:
  source_files:
    - tests/conda/tests.sh
  commands:
    - bash tests/conda/tests.sh
    - test -f "$PREFIX/bin/coble"
    - test -x "$PREFIX/bin/coble"

about:
  home: https://coble-tools.github.io/coble/
  license: MIT
  license_file: LICENSE
  summary: 'COBLE: COnda BuiLdEr'
  description: |
    A utility to help build conda environments for reproducibility in research software.
  dev_url: https://github.com/coble-tools/coble