#coble-yml
dependencies:
  - r_conda:
    - biocmanager    
    - devtools    
    - remotes    
    - data.table
  - bio_package:
    - fgsea
  - r_conda:
    - stringi
    - rcpp
    - plyr
    - reticulate
    - sitmo
    - seurat
    - units  
  - bio_package:
    - stJoincount
  - conda:
    - libxml2
    - pandoc
    - pypandoc
    - boost-cpp
  - r_conda:
    - xml
    - xlconnect
    - xml2
    - testthat
    - systemfonts
    - ragg  
  - conda:
    - fonts-conda-ecosystem
    - mscorefonts
  - r_conda:
    - nloptr
    - polyclip
  - r_package:
    - devtools
  - conda:
    - zlib
  - r_conda:
    - rsqlite
  - bio_package:
    - limma
    - vsn
    - edgeR
    - org.Hs.eg.db
    - org.Mm.eg.db
  - conda:
  - r_conda:
    - tzdb
    - vroom
    - readr
    - readxl
    - rcppannoy
    - glmnet
  - r_package:
    - gdata
  - wget:
    - https://cran.r-project.org/src/contrib/Archive/NanoStringNorm/NanoStringNorm_1.2.1.1.tar.gz    
  - r_package:
    - bedr
    - SIMMS
    - haven
    - foreign
    - spatstat
  - github:    
    - aroneklund/copynumber  
  - r_conda:    
    - rcpparmadillo
    - conquer
    - minqa
  - conda:
    - conda-forge::r-lme4
  - r_package:
    - FactoMineR
    - factoextra
    - knitr
    - rmarkdown
    - inline  
  - r_conda:
    - rjson
    - interp
  - bio_package:
    - biomaRt
    - rtracklayer
    - GenomicFeatures
    - BSgenome
    - VariantAnnotation
    - ensembldb
    - biovizBase
    - Gviz
    - GenomicInteractions
  - r_package:
    - distributions3
    - mboost
    - AER
    - brglm2
    - flexmix
    - modelsummary
    - nonnest2
    - tinytest
    - knitr
    - UpSetR
    - plotrix
    - gplots
    - drc
    - chicane
  - bash:
    - Rscript -e "install.packages('countreg', repos='http://R-Forge.R-project.org', dependencies = TRUE)"    
  - conda:
    - conda-forge::r-v8
  - bio_package:
    - multtest
    - GSEABase
    - cellHTS2
    - reshape
    - TeachingDemos
    - tidyverse
    - SingleR
    - scran
    - scater
    - celldex
    - MAST
    - impute
    - genefu
    - fastseg
    - methylKit
  - r_package:
    - tidyverse
    - argparser
    - stringdist
  - bio_package:
    - BSgenome.Hsapiens.NCBI.GRCh38
  - github:
    - Nik-Zainal-Group/signature.tools.lib
  - bio_package:
    - genomation
    - ggbio
    - TxDb.Hsapiens.UCSC.hg38.knownGene
  - r_package:
    - Signac
  - bio_package:
    - EnsDb.Hsapiens.v86
    - harmony
  - conda:
    - hdf5
  - r_package:
    - hdf5r  
  - r_conda:
    - rjags
  - bio_package:
    - infercnv
  - github:
    - hdng/clonevol
  - r_package:
    - packcircles 
  - r_conda:    
    - s2
    - Cairo
    - ggrastr
  - bash:
    - Rscript -e "remotes::install_github('GreenleafLab/ArchR', ref='master', repos = BiocManager::repositories())"
    - Rscript -e "ArchR::installExtraPackages()"
  - github:
    - satijalab/seurat-wrappers
  - bio_package:
    - ShortRead  
  - r_conda:
    - eulerr
  - bash:
    - Rscript -e "remotes::install_github('xmc811/Scillus', ref = 'development')"
  - github:
    - VanLoo-lab/ascat/ASCAT
    - chris-mcginnis-ucsf/DoubletFinder
  - r_package:
    - clustree
  - bio_package:
    - Chicago
  - wget:
    - https://github.com/carmonalab/STACAS/archive/refs/heads/master.zip
  - bio_package:
    - batchelor
  - wget:
    - https://cran.r-project.org/src/contrib/Archive/CIDER/CIDER_0.99.4.tar.gz
  - conda:
    - conda-forge::r-magick
  - bio_package:
    - GSVA
  - github:
    - cansysbio/ConsensusTME
  - conda:
    - conda-forge::r-gdtools
  - bio_package:
    - pcaMethods
  - bash:
    - git clone https://git.bioconductor.org/packages/DeconRNASeq
    - R CMD INSTALL DeconRNASeq
    - rm -rf DeconRNASeq
  - github:
    - EDePasquale/DoubletDecon
  - bio_package:
    - Rsubread  
  - r_package:
    - rstan
  - github:    
    - stan-dev/rstantools
    - davidaknowles/leafcutter/leafcutter
  - bio_package:
    - liftOver
  - conda:
  - r_conda:
    - seqminer
  - r_package:
    - squash
    - iotools  
  - wget:
    - https://cran.r-project.org/src/contrib/Archive/sequenza/sequenza_3.0.0.tar.gz
  - bio_package:
    - glmGamPoi
  - bash:
    - Rscript -e "remotes::install_github('satijalab/sctransform', ref = 'develop')"
  - r_package:
    - Ckmeans.1d.dp  
  - wget:
    - https://cran.r-project.org/src/contrib/Archive/modes/modes_0.7.0.tar.gz
  - r_package:
    - dynamicTreeCut
    - roll
    - hdf5r
  - conda:
    - conda-forge::r-units
    - conda-forge::r-sf
    - conda-forge::r-spdep
  - bash:
    - Rscript -e "remotes::install_github('cole-trapnell-lab/monocle3', ref='develop')"    
  - pip:
    - setuptools>=59.0
    - Cython>=3.0.11
    - pysam
    - git+https://github.com/rachelicr/pysamstats.git
  - r_package:
    - LDlinkR
    - randomForest
  - bio_package:
    - multiGSEA  
  - wget:
    - http://research-pub.gene.com/REdiscoverTEpaper/data/REdiscoverTEdata_1.0.1.tar.gz    
    - https://cran.r-project.org/src/contrib/Archive/Matrix.utils/Matrix.utils_0.9.8.tar.gz
  - github:
    - karakulahg/TEffectR
  - bio_package:
    - minfi
    - IlluminaHumanMethylationEPICanno.ilm10b4.hg19
    - IlluminaHumanMethylationEPICmanifest
    - missMethyl
    - minfiData
    - DMRcate
  - bash:
    - Rscript -e "BiocManager::install('preprocessCore', configure.args='--disable-threading', force = TRUE)"
  - r_package:
    - clusterSim
    - clv
  - github:
    - saeyslab/nichenetr
  - bio_package:
    - kstreet13/slingshot
  - conda:
    - conda-forge::r-ncdf4
  - r_package:
    - HiClimR
    - ccaPP
    - egg
  - bio_package:
    - sva
  - bash:
    - Rscript -e "remotes::install_github('digitalcytometry/cytotrace2', subdir = 'cytotrace2_r')" 
  - pip:
    - scanoramaCT
  - conda:
    - conda-forge::r-rpostgres
  - github:
    - PriceLab/ghdb
  - bio_package:
    - destiny
  - github:
    - sqjin/CellChat
  - r_package:
    - openssl
  - bash:
    - Rscript -e "install.packages('pracma', repos='http://R-Forge.R-project.org')"
  - github:
    - trevorld/r-optparse
  - conda:
  - r_conda:
    - mcmcpack
  - r_package:
    - mvtnorm
    - ellipse
    - coda
    - Matrix
    - Rtsne
    - gtools
    - foreach
    - doParallel
    - doSNOW
    - snow
    - lattice
    - MASS
    - bayesm
    - robustbase
    - chron
    - mnormt
    - schoolmath
    - RColorBrewer
  - bio_package:
    - DEXSeq  
  - r_conda:    
    - arrow
  - bio_package:
    - AUCell
    - RcisTarget
    - GENIE3
  - github:
    - bokeh/rbokeh
  - bio_package:
    - R2HTML
  - bash:
    - Rscript -e "remotes::install_github('aertslab/SCopeLoomR', build_vignettes = TRUE)"
  - github:
    - aertslab/SCENIC
  - r_package:
    - ISOpureR
    - DiffCorr
  - github:
    - broadinstitute/cdsr_models
    - PhanstielLab/Sushi
  - bio_package:
    - ChromSCape
  - bash:
    - Rscript -e "remotes::install_github('sztup/scarHRD', build_vignettes = TRUE)"
  - github:
    - guokai8/scGSVA
  - bio_package:
    - reactome.db
  - pip:
    - spatialde
  - r_package:
    - poolr
    - tsne
    - flexmix
    - fpc
  - github:
    - cit-bioinfo/mMCP-counter
    - mojaveazure/seurat-disk
  - r_package:
    - immunarch
    - strawr
  - github:
    - kharchenkolab/numbat
  - r_package:
    - keras
    - ijtiff
    - bbmle
  - github:
    - choisy/cutoff  
  - wget:
    - https://bioconductor.org/packages/3.19/bioc/src/contrib/zlibbioc_1.50.0.tar.gz
  - bio_package:
    - PoisonAlien/maftools
    - illuminaHumanv4.db
    - zellkonverter
    - NanoStringNCTools
    - GeomxTools
    - GeoMxWorkflows  
  - wget:
    - https://github.com/rachelicr/r-maptools/archive/refs/heads/main.zip
  - r_package:
    - openxlsx
  - r_package:  
    - terra
    - raster
  - bio_conda:
    - DelayedArray
  - bio_package:
    - IHW    
    - lpsymphony
    - maftools     
    - SparseArray
    - cellHTS2  
  - pip:
    - requests
  - bio_package:
    - Orthology.eg.db
  - r_package:
    - effsize
  - bio_package:
    - viper
    - dorothea
  - r_package:
    - enrichR
  - bio_package:
    - aracne.networks
    - scDblFinder
  - pip:
    - PyYAML
  - r_package:
    - languageserver
    - unigd
    - AsioHeaders  
  - wget:
    - https://cran.r-project.org/src/contrib/Archive/httpgd/httpgd_2.0.4.tar.gz
  - pip:
    - radian
  - github:
    - munoztd0/reprtree
  - r_package:
    - seqinr
  - wget:    
    - https://github.com/carmonalab/ProjecTILs/archive/refs/heads/master.zip
  - github:    
    - carmonalab/SignatuR
    - vladchimescu/lpsymphony
    - nignatiadis/IHW
    - saeyslab/multinichenetr
