##############################################################################
# YAML format for COBLE configuration
# code/coble.sh --results results/miniyml --input config/mini.yml --env miniyml --skip-errors
##############################################################################
coble:
  create:
    - miniyml
  channels:
    - defaults    
    - bioconda
    - conda-forge    
  packages:
    conda:
      - r-devtools      
    r:
      - biocmanager
      - knitr
      - lme4
      - easypar     
    bioc:
      - fgsea
    pip:
      - numpy
      - git+https://github.com/stan-dev/cmdstanpy.git@develop
      - git+https://github.com/ICR-RSE-Group/gitalma.git
    bash:    
    - echo "Hello World"    
    r-github:
      - seedgeorge/SQUEAK
    r-url:
      - https://cran.r-project.org/src/contrib/Archive/sequenza/sequenza_3.0.0.tar.gz
  
